#!/bin/bash
#
#	mp.sh
#
#	Runs mplay on an entire sequence.
#	Usage:
#
#	mp <frame file name from sequence>
#
#

echo mplay `echo $1 | sed -r 's/[0-9][0-9]+\./\$F4./'` 
mplay `echo $1 | sed -r 's/[0-9][0-9]+\./\$F4./'` 



